name: Nightly

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - LICENSE

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Package latest translations
      run: zip -r -v ../LastStarshipTranslations_alpha8_nightly.zip assets/ data/ ../README.md
      working-directory: ./latest

    - name: Package legacy translations
      run: |
        for d in */ ; do
          pushd "$d"
          zip -r -v "../../LastStarshipTranslations_${d%/}_nightly.zip" assets/ data/ ../README.md
          popd
        done
      working-directory: ./legacy

    - name: List files
      run: ls -R

    - name: Update git tag
      run: |
        git tag -f nightly
        git push -f origin nightly

    - name: Update nightly release
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "LastStarshipTranslations_*_nightly.zip"
        tag: "nightly"
        commit: ${{ github.ref_name }}
        prerelease: true
        allowUpdates: true
        updateOnlyUnreleased: true
        removeArtifacts: true