name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: 'X.Y{.Z}'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Use base64 README
      run: |
        rm README.md
        mv README-base64.md README.md

    - name: Package Files
      run: |
        mv latest/data data
        zip -r -v LastStarshipTranslations_v${{ github.event.inputs.version }}.zip data/ README.md

    - name: Release
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: 'LastStarshipTranslations_v${{ github.event.inputs.version }}.zip'
        tag: 'v${{ github.event.inputs.version }}'
        commit: ${{ github.ref_name }}
        prerelease: false
        allowUpdates: false
        artifactErrorsFailBuild: true
        draft: true